import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#292a2f",
        "tertiary": "#fbbc05",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#c2c6d5",
        "on-primary": "#002e69",
        "surface-container-highest": "#34343a",
        "secondary": "#6ddd81",
        "on-secondary": "#003914",
        "outline-variant": "#424753",
        "on-background": "#e3e2e9",
        "surface-dim": "#121318",
        "error": "#ffb4ab",
        "surface-container-low": "#1a1b20",
        "secondary-fixed-dim": "#6ddd81",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e3e2e9",
        "tertiary-fixed-dim": "#fbbc05",
        "on-primary-container": "#00285c",
        "surface-tint": "#adc6ff",
        "surface-container": "#1e1f24",
        "inverse-on-surface": "#2f3035",
        "surface": "#121318",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#005320",
        "on-secondary-container": "#003210",
        "primary": "#adc6ff",
        "error-container": "#93000a",
        "surface-bright": "#38393e",
        "background": "#121318",
        "surface-container-lowest": "#0d0e13",
        "on-surface": "#e3e2e9",
        "inverse-primary": "#005ac1",
        "on-primary-fixed-variant": "#004494",
        "on-secondary-fixed": "#002108",
        "on-primary-fixed": "#001a41",
        "on-tertiary-container": "#372700",
        "secondary-container": "#30a550",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-tertiary-fixed": "#261a00",
        "tertiary-container": "#b88900",
        "secondary-fixed": "#89fa9b",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#ffdfa0",
        "primary-container": "#4d8efe",
        "outline": "#8c909f",
        "surface-variant": "#34343a",
        "on-tertiary": "#402d00",
        dark: {
          bg: "#121318",
          surface: "#1a1b20",
          card: "#1e1f24",
          border: "#34343a",
          hover: "#292a2f",
        },
        accent: {
          DEFAULT: "#adc6ff",
          hover: "#d8e2ff",
          muted: "rgba(173, 198, 255, 0.15)",
        },
        lime: {
          DEFAULT: "#8BC34A",
          muted: "rgba(139, 195, 74, 0.15)",
        },
        category: {
          mouse: "#64B5F6",
          keyboard: "#CE93D8",
          headphones: "#FFB74D",
          mousepad: "#4DB6AC",
        },
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        heading: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["Reddit Mono", "Courier New", "monospace"],
      },
      boxShadow: {
        glow: "0 0 30px var(--glow-color)",
        "card-hover": "0 8px 32px rgba(0, 0, 0, 0.3)",
      },
      animation: {
        "fade-in-up": "fadeInUp 0.8s ease-out forwards",
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "scale-up": "scaleUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "shimmer": "shimmer 1.5s infinite",
        "gradient-x": "gradient 3s linear infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin 20s linear infinite",
        "spin-slow-reverse": "spin 25s linear infinite reverse",
        "float": "float 6s ease-in-out infinite",
        "float-delay": "float 7s ease-in-out 3.5s infinite",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0", filter: "blur(10px)" },
          "100%": { opacity: "1", filter: "blur(0)" },
        },
        scaleUp: {
          "0%": { transform: "scale(0.92)" },
          "100%": { transform: "scale(1)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        gradient: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(5deg)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
